platform :ios, '12.0'

target 'RestaurantsTest' do
  use_frameworks!

  # Pods for RestaurantsTest

  pod 'PureLayout'
  pod 'RxSwift'

  target 'RestaurantsTestTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'Quick'
    pod 'Nimble'

  end

end
